// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_chat from "./routes/api/chat.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_speak from "./routes/api/speak.tsx";
import * as $api_transcribe from "./routes/api/transcribe.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/chat.tsx": $api_chat,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/speak.tsx": $api_speak,
    "./routes/api/transcribe.tsx": $api_transcribe,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
